### PR TITLE
Retro68: generate and push docker image during Azure pipeline

### PR DESCRIPTION
**Pull request by mcayland**
I have been investigating using Retro68 to build Mac drivers for QEMU's 68k and PPC emulation, and as part of that work wanted to generate a docker image that can be used to build such drivers using CI. Here is a solution that takes the existing Dockerfile from the repository, brings it up to date, integrates the new image into the existing Azure pipeline and then adds a step to push the resulting image to the GitHub container registry (GHCR) for general use.

**NOTE:** since the GHCR integration requires service connections configured in Azure DevOps, this PR will need to be modified according to the setup on the official Retro68 pipeline. There is also an initial commit that will be dropped from the final PR that temporarily disables the non-Linux builds in order to save CI minutes during testing.

The provided Dockerfile updates change the build to be a multi-stage build which consists of 2 separate stages: a `build` stage which holds the complete image of the build environment (and is used to run the regression tests) and a `release` stage which is effectively a basic build environment with just the contents of the `toolchain/bin` directory added. The `build` stage is discarded immediately after the regression tests are run whereas the `release` stage is pushed to GHCR: by discarding the `build` stage the size of the final docker image is reduced from 9.6GB to 2.6GB.

To ensure that the Dockerfile is always up-to-date (and also save CI minutes) the Linux build job is converted from a host build to a container build: this is fairly straightforward, with the only changes being that the regression tests are run in a copy of the `build` stage container, with the CTest results being copied back out afterwards for use by the  `PublishTestResults@2` task.

I've run the updated Azure pipeline on my personal GitHub account to generate the release `retro68` docker image to demonstrate the final result which is available at https://github.com/mcayland?tab=packages.

Finally to demonstrate how this can be used for CI here is an example showing how to build the `Raytracer` sample from the upstream Retro68 repository using the Docker image without having to pre-install the toolchain:

```
$ git clone --depth 1 https://github.com/autc04/Retro68.git
$ cd Retro68
$ docker run --rm -v $(pwd):/root -i ghcr.io/mcayland/retro68 /bin/bash <<"EOF"
    cd Samples/Raytracer
    mkdir build && cd build
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/Retro68-build/toolchain/m68k-apple-macos/cmake/retro68.toolchain.cmake
    make
EOF
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /Retro68-build/toolchain/bin/m68k-apple-macos-gcc
-- Check for working C compiler: /Retro68-build/toolchain/bin/m68k-apple-macos-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Retro68-build/toolchain/bin/m68k-apple-macos-g++
-- Check for working CXX compiler: /Retro68-build/toolchain/bin/m68k-apple-macos-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/Samples/Raytracer/build
Scanning dependencies of target FixedBenchmark
[  9%] Building CXX object CMakeFiles/FixedBenchmark.dir/fixedbenchmark.obj
[ 18%] Building CXX object CMakeFiles/FixedBenchmark.dir/fixed.obj
[ 27%] Linking CXX executable FixedBenchmark.code.bin
[ 27%] Built target FixedBenchmark
Scanning dependencies of target FixedBenchmark_APPL
[ 36%] Generating FixedBenchmark.bin, FixedBenchmark.APPL, FixedBenchmark.dsk, FixedBenchmark.ad, %FixedBenchmark.ad
[ 36%] Built target FixedBenchmark_APPL
Scanning dependencies of target Raytracer2
[ 45%] Building CXX object CMakeFiles/Raytracer2.dir/raytracer2.obj
[ 54%] Building CXX object CMakeFiles/Raytracer2.dir/fixed.obj
[ 63%] Linking CXX executable Raytracer2.code.bin
[ 63%] Built target Raytracer2
Scanning dependencies of target Raytracer2_APPL
[ 72%] Generating Raytracer2.bin, Raytracer2.APPL, Raytracer2.dsk, Raytracer2.ad, %Raytracer2.ad
[ 72%] Built target Raytracer2_APPL
Scanning dependencies of target Raytracer
[ 81%] Building C object CMakeFiles/Raytracer.dir/raytracer.obj
[ 90%] Linking C executable Raytracer.code.bin
[ 90%] Built target Raytracer
Scanning dependencies of target Raytracer_APPL
[100%] Generating Raytracer.bin, Raytracer.APPL, Raytracer.dsk, Raytracer.ad, %Raytracer.ad
[100%] Built target Raytracer_APPL
```

The final contents of the CMake `build` directory on the host are now this:

```
$ ls -l Samples/Raytracer/build/
total 4792
-rw-r--r--  1 root root   14329 Oct 23 14:45 CMakeCache.txt
drwxr-xr-x 10 root root    4096 Oct 23 14:45 CMakeFiles
-rw-r--r--  1 root root    1389 Oct 23 14:45 cmake_install.cmake
-rw-r--r--  1 root root  744026 Oct 23 14:45 %FixedBenchmark.ad
-rw-r--r--  1 root root       0 Oct 23 14:45 FixedBenchmark.ad
-rw-r--r--  1 root root       0 Oct 23 14:45 FixedBenchmark.APPL
-rw-r--r--  1 root root  744192 Oct 23 14:45 FixedBenchmark.bin
-rw-r--r--  1 root root  744064 Oct 23 14:45 FixedBenchmark.code.bin
-rwxr-xr-x  1 root root 1167112 Oct 23 14:45 FixedBenchmark.code.bin.gdb
-rw-r--r--  1 root root  819200 Oct 23 14:45 FixedBenchmark.dsk
-rw-r--r--  1 root root    9039 Oct 23 14:45 Makefile
-rw-r--r--  1 root root   98941 Oct 23 14:45 %Raytracer2.ad
-rw-r--r--  1 root root       0 Oct 23 14:45 Raytracer2.ad
-rw-r--r--  1 root root       0 Oct 23 14:45 Raytracer2.APPL
-rw-r--r--  1 root root   99072 Oct 23 14:45 Raytracer2.bin
-rw-r--r--  1 root root   99072 Oct 23 14:45 Raytracer2.code.bin
-rwxr-xr-x  1 root root  156584 Oct 23 14:45 Raytracer2.code.bin.gdb
-rw-r--r--  1 root root  819200 Oct 23 14:45 Raytracer2.dsk
-rw-r--r--  1 root root   17278 Oct 23 14:45 %Raytracer.ad
-rw-r--r--  1 root root       0 Oct 23 14:45 Raytracer.ad
-rw-r--r--  1 root root       0 Oct 23 14:45 Raytracer.APPL
-rw-r--r--  1 root root   17408 Oct 23 14:45 Raytracer.bin
-rw-r--r--  1 root root   17408 Oct 23 14:45 Raytracer.code.bin
-rwxr-xr-x  1 root root   37592 Oct 23 14:45 Raytracer.code.bin.gdb
-rw-r--r--  1 root root  819200 Oct 23 14:45 Raytracer.dsk
```

### CODE REVIEW

**Comment by mcayland** [comment]
@autc04 No changes in the repushed branch other than to fix the "azure-piplines.yml" typo in the subject line of patch 6. Please let me know if you have any other comments or questions, as it would be great to automate the creation of up-to-date docker images in the upstream Retro68 pipeline!

**Comment by autc04** [comment]
Sorry for ignoring this amazing pull request for so long.

I love it.

Can you give me a quick hint / doc link for the gchr setup/service integration configuration? Never done that before.

**Comment by mcayland** [comment]
Fantastic! In order to allow Azure Devops to authenticate with your github account you need to create a personal access token with privileges that allow it to push to GHCR as per https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry. You can do this by logging into github and then from the menu go to Settings -> Developer Settings -> Personal Access Tokens -> Tokens (classic). As per the docs the token requires the `admin:repo_hook`, `read:user`, `repo`, and `user:email` privileges.

Once you have the token, log into Azure Devops and go to Project Settings -> Sevice Connections. Click "New Service Connection" and select type "Docker Registry". The Docker Registry URL is https://ghcr.io/autc04/, the Docker ID is your github username and the password is the token. The service connection name is the label used to reference the connection in `azure-pipelines.yml`: I used "mcayland-github-docker" but feel free to change it as you need.

Finally the last commit needs a few tweaks:

  * For the first `Docker@2` task change the `repository` URL to https://ghcr.io/autc04/retro68 (which will be the URL of the final image)
  * For the second and third `Docker@2` tasks change the `containerRegistry` from mcayland-github-docker to match the name of the Service Connection you created in Azure DevOps
  * In the third `Docker@2` task change `repository` from mcayland/retro68 to autc04/retro68

Give it a test at this point, and if all looks good you can drop the 1st commit which temporarily disables all the other non-Linux pipelines before merge.

When the pipeline has run successfully the package will appear in https://github.com/autc04?tab=packages although you will need to change the image from "Private" to "Public" to allow unauthenticated users to execute "docker run" as per above.

Hope this helps! And feel free to drop this PR and merge via a different branch that you've tested if that makes it easier :)

**Comment by mcayland** [comment]
@autc04 just a gentle ping to see if you were able to get the Azure DevOps bits and pieces up and running using the information above, and if there is anything else I can do to help get this merged?

**Comment by mcayland** [comment]
I found a bit of time to look at the Azure pipeline results above, and the build looks correct and it's just that the github token isn't allowing access to GHCR. It is possible to quickly check the token without having to do a full build by using docker to do a manual push to GHCR e.g.

```
mca@kentang:~$ mkdir -p /tmp/test && cd /tmp/test
mca@kentang:/tmp/test$ echo "FROM alpine" > Dockerfile
mca@kentang:/tmp/test$ docker build -t ghcr.io/mcayland/retro68-test .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM alpine
 ---> c059bfaa849c
Successfully built c059bfaa849c
Successfully tagged ghcr.io/mcayland/retro68-test:latest
mca@kentang:/tmp/test$ export GITHUB_TOKEN=ghp_XXXXXXXXXXXXXXXXXXX
mca@kentang:/tmp/test$ echo $GITHUB_TOKEN | docker login ghcr.io -u mcayland --password-stdin
WARNING! Your password will be stored unencrypted in /home/mca/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
mca@kentang:/tmp/test$ docker push ghcr.io/mcayland/retro68-test
Using default tag: latest
The push refers to repository [ghcr.io/mcayland/retro68-test]
8d3ac3489996: Layer already exists 
latest: digest: sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 size: 528
```

This then causes the test image to appear at https://github.com/mcayland?tab=packages.

The changes to the docker connection look correct, so once the token is working as above then it should just be a case of fixing the Docker registry connection details in Azure DevOps. I can also repush the branch with those changes incorporated if you prefer.

**Comment by mcayland** [comment]
@autc04 a quick festive ping to see if there is anything I can do to help with this PR and its follow-up https://github.com/autc04/Retro68/pull/216?

**Comment by autc04** [comment]
Thanks for the ping. It is time.

I tried again to wrestle with the cursed beast that is ADO & docker...

I was stuck for a long time with ADO telling me "unauthorized: unauthenticated: User cannot be authenticated with the token provided."
Which was annoying, as the token *did* work perfectly to push images from my local machine, and I had no way to find out what was different on ADO...

This time I tried pushing the image using the command line, passing a token explicitly (no service connection), and suddenly ADO's variables mechanism refused to acknowledge that I had added another variable. It only showed the variable I'm using for pushing `nix` buildst to cachix.org, not the second one I had added.
And then I tried setting it up using a variable group, and suddenly it started working. Still no clue what I did wrong in my previous attempts, though.

Anyway, running one final test build from my own `docker-build` branch, then I'll merge.

**Comment by autc04** [comment]
... and it's finally in!

Thanks for your contribution!
... and for your amazing patience ;-)

**Comment by mcayland** [comment]
Fantastic, thank you so much! I have no idea why the service connection didn't work in your case, but I can now see the generated docker image in the packages tab. This is exactly what is needed to use Retro68 to start building 68K/PPC MacOS drivers for QEMU :)

**Pull request closed without merging**
