### PR TITLE
LaunchAPPL: Fix two macOS Mini vMac launching bugs

### PR DESCRIPTION
**Pull request by ryandesign**
On all macOS versions, Mini vMac would launch behind other applications
because it was being launched by running the executable within the
application bundle directly. The solution is to let the OS launch the
app normally by using the `open` utility. This eliminates the 30 lines of
code that laboriously determined the executable name.

On macOS 10.12 and later, Mini vMac could not find the ROM or disk
files. These files were being placed in the same directory as the Mini
vMac application, but a new macOS security measure called Gatekeeper
Path Randomization or App Translocation prevents that from working
anymore. See https://www.gryphel.com/c/minivmac/osx_note.html. The
solution is to place the ROM and disk files within the mnvm_dat
directory in the Contents directory in the application bundle.

The code that copies Mini vMac into the temporary directory had to be
moved earlier so that when the ROM file is symlinked and the disk image
is created the mnvm_dat directory into which they go will be there.

Since more than one method needed to know whether Mini vMac was an app
bundle, a Boolean instance var was added on macOS to indicate that.

----

I have only tested this on macOS 12 but I think it is correct for other systems too.

### CODE REVIEW

**Comment by ryandesign** [comment]
The checks succeeded on Linux, failed on macOS due to #158, and failed on all Nix runners in the "Push to Cachix" step.

**Comment by autc04** [comment]
looking into the cachix failure; azure didn't do what I wanted it to today, will try again tomorrow :-)

**Comment by autc04** [comment]
Just for the record, this will probably break things on Mac OS 10.4 Tiger (some of the options to `open` weren't supported yet)
... but we probably should not care.

People who use Tiger probably want to launch the resulting applications directly on Tiger anyway.

**Comment by autc04** [comment]
For the record: this will break on Tiger (10.4), as `open` didn't support all arguments yet.

This shouldn't be problem, as people running on Tiger will probably want to launch the apps directly without using MiniVMac.

**Comment by ryandesign** [comment]
Ah darn, you're right. `-a` first appeared in Tiger while `-n` and `-W` first appeared in Leopard. I was misled by the "February 10, 2004" date at the bottom of the `open` manpage in Leopard. Since that date is more than a year before the release of Tiger I assumed those features were in Tiger, but I guess they forgot to update the date when they added the new features.

Instead of using `ChildProcess` to call `open` to launch Mini vMac, one could probably rewrite this code to use [NSWorkspace](https://developer.apple.com/documentation/appkit/nsworkspace?language=objc) to launch it but I don't have experience with that.

**Comment by autc04** [comment]
Indeed, that would probably be the way to go, but as I said, I think the only point of running Retro68 on a 10.4 Mac would be to actually target that old Mac, and not to use minivmac. So I think we can safely ignore this remaining issue.

**Pull request merged**
